Repository OpenVoiceOS/ovos-config, pull requests merged in 2023-12, with the labels that each got.

#85 feat/lang_utils
  ovos_config/locale.py
Labels: enhancement

#86 Force websocket to bind on 127.0.0.1
  ovos_config/mycroft.conf
Labels: bug

#88 fix/untangle_from_LF
  ovos_config/locale.py
Labels: bug

#89 fix circular import
  ovos_config/meta.py
Labels: bug

#90 drop mycroft-core config location
  ovos_config/locations.py
  test/unittests/test_locations.py
Labels: bug

#93 document transformer plugins
  ovos_config/mycroft.conf
Labels: documentation
