Repository OpenVoiceOS/ovos-config, pull requests merged in 2024-06, with the labels that each got.

#126 fix/typo
  ovos_config/mycroft.conf
Labels: bug

#127 fix: unbound local var
  .github/workflows/build_tests.yml
  .github/workflows/install_tests.yml
  .github/workflows/unit_tests.yml
  ovos_config/__main__.py
  ovos_config/models.py
  ovos_config/utils.py
  requirements/tests.txt
Labels: bug

#133 better listener defaults
  ovos_config/mycroft.conf
Labels: enhancement

#134 fix config set
  ovos_config/__main__.py
Labels: bug

#136 Update mycroft.conf
  ovos_config/mycroft.conf
Labels: documentation

#128 feat: add /usr/share as a config location
  .gitignore
  ovos_config/config.py
  ovos_config/locations.py
  ovos_config/meta.py
  ovos_config/models.py
  test/unittests/test_locations.py
Labels: enhancement

#137 revert to single thread
  ovos_config/mycroft.conf
Labels: bug
